// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChampions():Promise<Array<main.Champion>>;

export function GetConfig():Promise<main.Config>;

export function GetStatus():Promise<main.LCUStatus>;

export function GoToMainMenu():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ReconnectLCU():Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function StartRankedQueue():Promise<void>;
