// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChampions() {
  return window['go']['main']['App']['GetChampions']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGameVersion() {
  return window['go']['main']['App']['GetGameVersion']();
}

export function GetPlayerProfile() {
  return window['go']['main']['App']['GetPlayerProfile']();
}

export function GetRankedStats() {
  return window['go']['main']['App']['GetRankedStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GoToMainMenu() {
  return window['go']['main']['App']['GoToMainMenu']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReconnectLCU() {
  return window['go']['main']['App']['ReconnectLCU']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartRankedQueue() {
  return window['go']['main']['App']['StartRankedQueue']();
}
